[book]
authors = ["BruceMaa"]
language = "zh-Hans"
multilingual = false
src = "src"
title = "Hadoop3 Doc"
description = "Hadoop3官方文档中文翻译"

[build]
build-dir = "docs"
create-missing = true

[output.html]
default-theme = "light"
curly-quotes = true
mathjax-support = false
google-analytics = "UA-82993633-1"
no-section-label = false
git-repository-url = "https://github.com/BruceMaa/Hadoop3-doc"
git-repository-icon = "fa-github"

[output.html.playpen]
editable = true
copy-js = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true